server:
  port: 8080

spring:
  application:
    name: viatrial-backend
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/viatrial.db
    hikari:
      connection-init-sql: PRAGMA foreign_keys=ON

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
